### ISSUE TITLE
Can't update fields throwing error

### ISSUE THREAD

**Issue by dapicella** [bcolpaert/Colso.Xrm.AttributeEditor#12]
Hello,

I just updated to 2018.3 and I can't update fields anymore as it is throwing an error when I hit save & publish. All I'm doing is updating the display name. Thanks. :

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Colso.Xrm.AttributeEditor.AppCode.AttributeTypes.PicklistAttribute.<AddAdditionalMetadata>b__8_1(String[] x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Colso.Xrm.AttributeEditor.AppCode.AttributeTypes.PicklistAttribute.AddAdditionalMetadata(PicklistAttributeMetadata attribute)
   at Colso.Xrm.AttributeEditor.AppCode.AttributeTypes.AttributeMetadataBase`1.GetAttributeMetadata()
   at Colso.Xrm.AttributeEditor.AppCode.AttributeTypes.AttributeMetadataBase`1.UpdateAttribute(IOrganizationService service)
   at Colso.Xrm.AttributeEditor.AttributeEditor.<>c__DisplayClass40_0.<SaveChanges>b__2(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by bcolpaert** [comment]
Hi dapicella, 

I could not reproduce the issue. Updating the displayname of an optionset is working in my test scenario. 
Are you changing the options or only the attribute display name?
Can you send me the excel, so I can investigate this?
